In [82]:
import numpy as np
import functools

In [18]:
# Create a zero array of size (3,3)
m = np.zeros((3,3))
print(m)
print(m.shape)
print(m.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
float64


In [38]:
# Create a zero array of size (3,3) of certain data type (e.g., uint8)
m = np.zeros((3,3), dtype=np.uint8)
print(m.dtype)

uint8


In [39]:
# How to change the dtype of an existing array?
m = m.astype(np.float64)
print(m.dtype)

float64


In [40]:
# How to create an array with 1s?
m = np.ones((3,3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
# Let's say we are given an array and want to create a new array which the same size but the values v=3
m1 = np.full(m.shape, 3)
print(m1)
# OR
m2 = np.full_like(m, 3)
print(m2)

# Note: There also exist functions such as ones_like and zeros_like

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [42]:
# What if we want to set all values of a matrix to a certain value?
m.fill(20) # In-place operation
print(m)
# OR
m[:] = 10
print(m)

[[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [121]:
# How do we alter the second row?
m[1,:] = 100
print(m)
# How do we edit the second column?
m[:,1] = 200
print(m)

[[  1. 202.   1.]
 [100. 100. 100.]
 [  0. 202.   1.]]
[[  1. 200.   1.]
 [100. 200. 100.]
 [  0. 200.   1.]]


In [122]:
# What happens if we run m[-1]?
print(m[-1]) # We get the LAST row of the matrix. NO out-of-bound exception!

[  0. 200.   1.]


In [130]:
# How to get all values greater than 10?
m = np.array([[1, 20, 30],[1,1,1]])
print('Mask', m>10)
print(m[m>10])
print('===')
# How to add 1 to all of those values and preserve the initial matrix?
m[m>10] += 1
print(m)
m[m>10] = m[m>10] + 1
print(m)

Mask [[False  True  True]
 [False False False]]
[20 30]
===
[[ 1 21 31]
 [ 1  1  1]]
[[ 1 22 32]
 [ 1  1  1]]


In [124]:
# How can we convert an existing list into a numpy array
l = [1,2,3]
m = np.array(l)
print(m, type(m))

# Note, that m is a copy of l. Hence, both objects are independent from each other.
l[0] = 10
m[2] = 10
print(l, m)

# But if we write ...
m = np.asarray(l)
m[0] = 10
l[2] = 10
print(l, m) # The matrix just re-used the list's memory. Modifying m alters l.

[1 2 3] <class 'numpy.ndarray'>
[10, 2, 3] [ 1  2 10]
[10, 2, 10] [10  2  3]


In [60]:
# How can we create a list of values ranging from 10 to (excl.) 200 (stepsize 15)?
l = range(10, 200, 15)
print(l) # Not a list yet. But it's iterable (that's why we can use it for, i.e. for loops)
l = list(range(10, 200, 15))
print(l)

range(10, 200, 15)
[10, 25, 40, 55, 70, 85, 100, 115, 130, 145, 160, 175, 190]


In [61]:
# How do we invert a list?
print(l[::-1])

[190, 175, 160, 145, 130, 115, 100, 85, 70, 55, 40, 25, 10]


In [63]:
# How do we fetch every second element from a list?
print(l[::2])

[10, 40, 70, 100, 130, 160, 190]


In [64]:
# How do we get the third last element?
print(l[-3])

160


In [66]:
# How do we create an identity matrix?
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
# How do we transpose a matrix?
m = identity
m[0,2] = 1
print(m)
m_t = m.T
print(m_t)

[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [69]:
# How do we multiple matrices element-wise?
m_mult = m * m_t
print(m_mult)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
# How do we calculate the dot-product of two matrices
m_dot = np.dot(m, m_t)
print(m_dot)

[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [74]:
# How to create a LIST of values of 4s (compact syntax)
# List comprehension
l = [4 for _ in range(10)]
print(l)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [78]:
# How to modify each element of the list using a function
def pow(x):
    return x**2

l_pow = [pow(x) for x in l]
print(l_pow)

# In-Place methods using lambda + map
l_pow_iter = map(lambda x: x**2, l) 
print(l_pow_iter) # Returns an iterator
l_pow = list(l_pow_iter)
print(l_pow)

[16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
[16, 16, 16, 16, 16, 16, 16, 16, 16, 16]


In [98]:
# Map, Filter and reduce are great tools to create "processing chains" (e.g., apply a series of functions in a row)
# 1. Remove all 4 from the list
# 2. Add +1 to every element
# 3. Compute the sum of all elements using reduce
l1 = [1,4,4,4,1,1,1]
c1 = filter(lambda x: x!=4, l1)
c2 = map(lambda x: x+1, c1)
c3 = functools.reduce(lambda x,y: x+y, c2)
result = c3
print(result)

8


In [103]:
# Let's assume that we have to lists (same length) and we want to element-wise merge the two lists
xs = [1,2,3]
ys = [-1,-2,-3]
merged = list(zip(xs, ys))
print(merged)

# How to invert the process?
split = list(zip(*merged))
xs, ys = split[0], split[1]
print(xs, ys)

[(1, -1), (2, -2), (3, -3)]
(1, 2, 3) (-1, -2, -3)
