# NumPy: The basic

NumPy, short for **Numerical Python**, is one of the most important foundational packages for numerical computing in Python. Many computational packages providing scientific functionality use NumPy's array objects as one of the standard interface *lingua francas* for data exchange.

Some of the things you will find in Numpy:
- *ndarray*, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities
- Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops
- Tools for reading/writing array data to disk and working with memory-mapped
files
- Linear algebra, random number generation, and Fourier transform capabilities
- A C API for connecting NumPy with libraries written in C, C++, or FORTRAN

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. 

**There are a number of reasons for this:**
    
- NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy's library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences.
- NumPy operations perform complex computations on entire arrays without the need for Python for loops, which can be slow for large sequences. NumPy is faster than regular Python code because its C-based algorithms avoid overhead present with regular interpreted Python code.

# Import numpy

The numpy module can be imported using `import numpy`. The alias `np` is commonly used for `numpy`.

In [79]:
import numpy as np

## Array Creation

NumPy arrays can be defined using Python sequences such as lists and tuples.

In [80]:
# Creates a 1-dimensional numpy array (matrix)
m = np.array([1, 2, 3])
print(m)

# The list becomes an ndarray object
print(type(m))

# The ndim attribute returns the number of dimensions ==> 1
print(m.ndim)

# The data type is int64 (or float32; platform dependent) as the values contained in the list are integers
# If Numpy encounters at least one float, the dtype of the matrix will be float64 (or float32)
print(m.dtype)

[1 2 3]
<class 'numpy.ndarray'>
1
int64


**Remark:**
    
The default NumPy behavior is to create arrays in either 32 or 64-bit signed integers (platform dependent and matches C long size) or double precision floating point numbers. If you expect your integer arrays to be a specific type, then you need to specify the dtype while you create the array.

Of course, we can also create multi-dimensional matrices. We only have to pass a nested list.

In [81]:
m = np.array([[1, 2, 3], 
              [10, 11, 11]])

# Note that each list becomes a ROW
print(m)

# Shape of the matrix
# It's a 2x3 matrix ==> <rows> x <columns>
print(m.shape)


[[ 1  2  3]
 [10 11 11]]
(2, 3)


We can also manually specify the data type by setting the `dtype` param.

A list of available `dtypes` can be found here: https://numpy.org/doc/stable/user/basics.types.html

In [82]:
m = np.array([1, 2, 3], dtype=np.uint8)
print(m)
print(m.dtype)

[1 2 3]
uint8


Now only integer values in the range from -128 to 127 can be represented by the matrix.

**Caution: If you try to store a value outside this range, Numpy will NOT raise an error.** (apparently, Numpy devs plan to change this behavior though)

In [83]:
m[0] = 1000

/tmp/ipykernel_141987/1819778962.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  m[0] = 1000


In [84]:
print(m)

[232   2   3]


If you are unsure of what range is supported by a specific data type, you can use the `np.iinfo()` or `np.finfo()` method. This method returns the machine limits for a given data type.

In [85]:
# Machine limits for floating point types
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [86]:
# Machine limits for int point types
np.iinfo(np.uint64)

iinfo(min=0, max=18446744073709551615, dtype=uint64)

### Some best practices for creating arrays

#### Function: np.arange()

`np.arange` creates arrays with regularly incrementing values. In terms of its output it is similar to running `np.array(range(1, 10))`. However, unlike `range()`, `np.arange()` also supports floating point values.

In [87]:
# Create an np.array with ints from 1 to (excl.) 10
m = np.arange(1, 10)

print(m)
print(m.dtype)

[1 2 3 4 5 6 7 8 9]
int64


In [88]:
# Create an np.array with floats from 1 to (excl.) 10
m = np.arange(1., 10.)

print(m)
print(m.dtype)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [89]:
# Create an np.array with floats from 1 to (excl.) 10. However, the step size should be 0.2
m = np.arange(1., 10., 0.2)

print(m)
print(m.dtype)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
float64


#### Function: np.linspace()

`np.linspace()` will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. The output data typed is always float.

In [90]:
m = np.linspace(1, 10, 1)

print(m)

[1.]


#### Function: np.eye()

Creates an identity matrix of a given size.

In [91]:
# Creates an identity matrix of size 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Function: numpy.diag()

Extract a diagonal or construct a diagonal array.

In [92]:
# Create a 3x3 matrix with the values [1,2,3] along the diagonal
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [93]:
# np.diag() will extract the values along the diagonal if we pass a 2d-array
np.diag([[1, 0, 4],
         [2, 2, 0],
         [0, 0, 3]])

array([1, 2, 3])

#### Function: np.ones(), np.zeros(), np.full()

Creates an array filled with the specified value.

In [104]:
# Creates a 4x2 matrix of 1s
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [105]:
# Creates a 4x2 matrix of 0s
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [106]:
# Creates a 4x2 matrix of 5s
np.full((4,2), fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

#### Function: np.ones_like(), np.zeros_like(), np.full_like()

Behaves similar to `np.ones()`, `np.zeros()`, `np.full()`. <br/>
However, instead of the providing the shape of a matrix, we directly provide a matrix. The function then copies the shape of the given matrix.

In [107]:
template_matrix = [[1, 2, 3], 
                   [1, 2, 3]]

In [108]:
np.ones_like(template_matrix)

array([[1, 1, 1],
       [1, 1, 1]])

In [109]:
np.zeros_like(template_matrix)

array([[0, 0, 0],
       [0, 0, 0]])

In [110]:
np.full_like(template_matrix, 5)

array([[5, 5, 5],
       [5, 5, 5]])

### Creating random numbers

Sometimes we need random numbers. Numpy offers a large variety of function for creating matrices with random numbers.

In [114]:
# Sample values from a uniform distribution in the range [0, 1). 
# Creates a matrix of size 6x3
m = np.random.rand(6, 3)

print(m)

[[0.56296477 0.40660496 0.29555372]
 [0.34095028 0.92518701 0.39468034]
 [0.73181648 0.79457822 0.29150436]
 [0.31882976 0.15417473 0.93534527]
 [0.32937954 0.68329234 0.48358203]
 [0.0731222  0.26662191 0.74936632]]


In [115]:
# Sample values from a standard normal distribution (mean=0, var=1)
# Creates a matrix of size 6x3
m = np.random.randn(6, 3)

print(m)

[[-0.16017929  1.35638111  0.52409248]
 [-0.52826872 -0.52858929  0.49310596]
 [-1.3902875  -0.36804681  1.47792148]
 [-0.43005312 -0.03945756  0.64369272]
 [ 0.0715172   0.686191    0.65509169]
 [ 0.70499579 -0.02302681  0.09354066]]


In [122]:
# Return random integers from low (inclusive) to high (exclusive).
m = np.random.randint(1, 4, size=(6,4))

print(m)

[[3 2 3 3]
 [1 1 3 3]
 [1 2 1 1]
 [1 3 2 2]
 [3 1 3 3]
 [1 3 1 3]]
