# NumPy: Indexing and Slicing

`ndarray` can be indexed using the standard Python `x[obj]` syntax, where `x` is the array and `obj` the selection. <br/>
There are different kinds of indexing available depending on `obj`: basic indexing, advanced indexing and field access.

In [2]:
import numpy as np

## Basic indexing

Thus far we have seen that we can access the contents of a NumPy array by specifying an integer or slice-object as an index for each one of its dimensions. Indexing into and slicing along the dimensions of an array are known as **basic indexing**.

The following example illustrates how we can index or slice a 1d array.

In [3]:
m = np.arange(10)

print(m)

# Indexing: Get the element at pos 5
print(m[5])

# Indexing: Get the second last element
print(m[-2])

# Slicing: Get a slice of elements starting at pos for 5 up to (incl) 7
print(m[5:8])

# Slicing: Get a slice of elements starting at pos for 3 to the (incl.) second last element 
# (assuming that the size of the array is unknown)
print(m[3:-1])

# Slicing: Get a slice of elements starting from the second last element down to (incl.) fifth last element
# (assuming that the size of the array is unknown)
print(m[-2:-6:-1])

[0 1 2 3 4 5 6 7 8 9]
5
8
[5 6 7]
[3 4 5 6 7 8]
[8 7 6 5]


**Hint:** `m[start:stop:step]`. In case of negative indices simply calculate `pos_index=len(m)-index` to determine the position. If `pos_start` is larger than `pos_stop`, the step step size `s` needs to be negative. Otherwise, the result is an empty matrix

If we are dealing with higher-dimensional matrices, we have to specify the slices for each dimension.

In [4]:
m = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print(m)

# Indexing: Select the element in the first row and second column
print(m[0, 1])

# Slicing: Obtain the second column
print(m[:, 1])

# Slicing: Obtain the first two elements in the second column
print(m[:2, 1])

# Slicing: Obtain the last two columns
print(m[:, -2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 5 8]
[2 5]
[[2 3]
 [5 6]
 [8 9]]


**Remark:** Note that slicing tuple can always be constructed as obj and used in the `x[obj]` notation. Slice objects can be used in the construction in place of the`[start:stop:step]` notation. For example,`x[1:10:5, ::-1]` can also be implemented as `obj = (slice(1, 10, 5), slice(None, None, -1)); x[obj]`

We can also use the built-in **Ellipsis object** `(...)` in order to insert slices into our index such that the index has as many entries as the array has dimensions. In the same way that `:` can be used to represent a slice object, `...` can be used to represent an Ellipsis object.


In [5]:
# Create a matrix with 3-dimensions
m = np.arange(3**3).reshape((3,)*3)
print(m)
print(m.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3)


In [6]:
# Slicing with Ellipse Operator
# The expression below is equivalent to m [:, :, 0]
print(m[..., 0])

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [7]:
# Slicing with Ellipse Operator
# The expression below is equivalent to m [0, :, :]
print(m[0, ...])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Slicing with Ellipse Operator
# The expression below is equivalent to m [0, :, 2]
print(m[0, ..., 2])

[2 5 8]


### Modifying the matrix

**Basic Indexing or Slicing** returns a view of the initial matrix. Hence, altering the matrix alters the inital matrix. If we don't want to alter the initial matrix, we have to create a copy of the matrix with `copy()`.

In [34]:
m = np.arange(2**2).reshape((2,)*2)

# Create a view
view = m[0, :]

# Alter the view
view[0] = 10

# We have altered the original array
print(m)
print(view)

[[10  1]
 [ 2  3]]
[10  1]


If we do not like this behavior, we have to create a copy explicitly.

In [36]:
m = np.arange(2**2).reshape((2,)*2)

# Create a copy
copy = m[0, :].copy()

# Alter the copy
copy[0] = 10

# The original matrix has not been affected
print(m)
print(copy)

[[0 1]
 [2 3]]
[10  1]


## Advanced indexing

Advanced indexing is triggered when the selection object, obj, is a non-tuple sequence object (as in the , an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool). There are two types of advanced indexing: integer and Boolean.

### Integer array indexing

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indices into that dimension.

Negative values are permitted in the index arrays and work as they do with single indices or slices:

In [164]:
m = np.arange(10)

print(m)

[0 1 2 3 4 5 6 7 8 9]


In [165]:
# Indexing with a list
print(m[[0, 5, 9]])

# Indexing with a list
print(m[[0, 5, -1]])

[0 5 9]
[0 5 9]


In [169]:
m = np.arange(25).reshape(5, 5)

print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [170]:
# Select the first row and last row
print(m[[0, -1]])

# Select the first column and last column
print(m[:, [0, -1]])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]
[[ 0  4]
 [ 5  9]
 [10 14]
 [15 19]
 [20 24]]


In [171]:
# Select the first element in the first and last row
print(m[[0, -1], 0])
# Hint 0 is broadcasted to [0,0]. Hence we get the elements (0,0) and (-1,0)

# Select the last element in the first and last row
print(m[[0, -1], -1])
# Hint -1 is broadcasted to [-1,-1]. Hence we get the elements (0,-1) and (-1,-1)

[ 0 20]
[ 4 24]


In [172]:
# Get the corner elements
row_idx = [[0, 0], [4, 4]]
col_idx = [[0, 4], [0, 4]]
print(m[row_idx, col_idx])

# Or ...
print(m[[[0, 0], [-1, -1]], [[0, -1], [0, -1]]])
# We get the elements at (0,0), (0,-1), (-1,0), (-1,-1)

[[ 0  4]
 [20 24]]
[[ 0  4]
 [20 24]]


### Modifying the matrix

Note that unlike basic indexing, advanced indexing does not return a view but a copy. Hence, altering the (adv.) indexed matrix does not alter the array.

In [40]:
m = np.arange(4).reshape(2, 2)

# Try to create a view to verify whether this is a view or not
view = m[:, [1]]

# Try to modify an element in the view
view[0, 0] = 10

# m has NOT been altered. <view> is a copy!
print(m)
print(view)

[[0 1]
 [2 3]]
[[10]
 [ 3]]


Note that we can still alter elements in the matrix using advanced indexing.

In [41]:
m = np.arange(4).reshape(2, 2)

# This still works. See https://stackoverflow.com/questions/15691740/does-assignment-with-advanced-indexing-copy-array-data
m[[0]] = 10.

print(m)

[[10 10]
 [ 2  3]]


### How to tell if the array is a view or a copy?

The `base` attribute of the ndarray makes it easy to tell if an array is a view or a copy. The `base` attribute of a view returns the original array while it returns `None` for a copy.

In [56]:
m = np.arange(4).reshape(2, 2)

print(m[:].base)

# None ==> Copy
print(m[[0, 1]].base)


[0 1 2 3]
None


### np.newaxis or None

A **newaxis object** (`np.newaxis`) in the selection tuple serves to expand the dimensions of the resulting selection by one unit-length dimension. The added dimension is the position of the newaxis object in the selection tuple. newaxis is an alias for `None`, and `None` can be used in place of this with the same result. From the above example:

In [173]:
m = np.arange(9).reshape(3, 3)

print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [174]:
print(m[np.newaxis, ...].shape)
print(m[..., np.newaxis].shape)
print(m[:, np.newaxis, :].shape)

# Or
print(m[:, None, :].shape)

(1, 3, 3)
(3, 3, 1)
(3, 1, 3)
(3, 1, 3)


This can be handy to combine two arrays in a way that otherwise would require explicit reshaping operations. For example:

In [186]:
m = np.arange(5)

# m[np.newaxis, :] => 1 x 5
# m[:, np.newaxis] => 5 x 1
# Broadcasting (1,5) + (5,1) = (5, 5)
m = m[np.newaxis, :] + m[:, np.newaxis]

print(m)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


## Boolean array indexing

This advanced indexing occurs when `obj` is an array object of Boolean type, such as may be returned from comparison operators. A single boolean index array is practically identical to`x[obj.nonzero()]` where, as described above,`obj.nonzero()` returns a tuple (of length `obj.ndim`) of integer index arrays showing the True elements of `obj`.

In [176]:
m = np.arange(9).reshape(3, 3)

print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [177]:
# Select the first row with a boolean array
# Note that the output is a 2d matrix since we use list indexing
print(m[[True, False, False]])

# Select the center element + the one the right
print(m[[False, True, False], [False, True, False]])

[[0 1 2]]
[4]


In [178]:
# Select all elements greater than 4
print(m[m > 4])

[5 6 7 8]


A common use case for this is filtering for desired element values. For example, one may wish to select all entries from an array which are not `NaN`:

In [179]:
m = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])

print(m[~np.isnan(m)])

[1. 2. 3.]


## Transposing Arrays and Swapping Axes

**Transposing** is a special form of reshaping that similarly returns a **view** on the underlying data without copying anything. Arrays have the transpose method and the special `T` attribute:

In [70]:
m = np.array([[0, 1], [2, 3]])

print(m)
print(m.T)

print('copy' if m.T.base is None else 'view')

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
view
