# NumPy: Essential Functions

In [3]:
import numpy as np

## Universal functions

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In NumPy, universal functions are instances of the `np.ufunc` class. Many of the built-in functions are implemented in compiled C code. The basic ufuncs operate on scalars, but there is also a generalized kind for which the basic elements are sub-arrays (vectors, matrices, etc.), and broadcasting is done over other dimensions.

Note that the output of the ufunc (and its methods) is not necessarily an ndarray.

### Unary ufuncs

Unary ufuncs are functions that take **one** ndarray as their input. 

For example:

- np.abs(array): To calculate absolute value of each value of the array.
- np.sqrt(array): To calculate square root of each value of the array.
- np.exp(array): To calculate exponential value of each element of the array.
- np.square(array): To calculate square of each value of the array.
- np.sin(array): To find the sine value of each data in the array.
- np.cos(array): To find the cos value of each data in the array.
- np.tan(array): To find the tan value of each data in the array.
- np.log(array): To find the natural logarithm (base e)
- np.loglog10(array): To find the logarithm (base 10)

In [8]:
m = np.arange(4).reshape(2, 2)

print(np.sqrt(m))
print(np.sin(m))

[[0.         1.        ]
 [1.41421356 1.73205081]]
[[0.         0.84147098]
 [0.90929743 0.14112001]]


Other unary functions:

- np.sum(array): Sum of array elements over a given axis.
- np.max(array): Return the maximum of an array or maximum along an axis.
- np.mean(array): Mean of an array or mean along an axis.
- np.cumsum(array): Cummulative sum of an array or cumsum along an axis

In [50]:
m = np.arange(6).reshape(2, 3)

# Hint: m has shape 2 x 3 (num_rows x num_cols)
# axis=0 => [:, 0] and [:, 1]

print(m)
print('=======')

print('Sum:', np.sum(m))
print('Sum along the 0st axis:', np.sum(m, axis=0)) # Along the cols
print('Mean:', np.mean(m))
print('Mean along the 0st axis:', np.mean(m, axis=0)) # Along the cols
print('Max:', np.max(m))
print('Max along the 1st axis::', np.max(m, axis=1)) # Along the rows
print('Min:', np.min(m))
print('Cumsum:', np.cumsum(m))
print('Cumsum along the 0st axis:', np.cumsum(m, axis=0)) # Along the cols

[[0 1 2]
 [3 4 5]]
Sum: 15
Sum along the 0st axis: [3 5 7]
Mean: 2.5
Mean along the 0st axis: [1.5 2.5 3.5]
Max: 5
Max along the 1st axis:: [2 5]
Min: 0
Cumsum: [ 0  1  3  6 10 15]
Cumsum along the 0st axis: [[0 1 2]
 [3 5 7]]


In [51]:
m = np.arange(2**3).reshape(2, 2, 2)

# Hint: m has shape 2 x 2 x 2
# axis=0 => [:, 0, 0] and [:, 0, 1] and [:, 1, 0] and [:, 1, 1]

print(m)
print('=======')

print('Sum along the 0st axis:', np.sum(m, axis=0))
print('Mean along the 0st axis:', np.mean(m, axis=0))
print('Max along the 1st axis::', np.max(m, axis=1))
print('Cumsum along the 0st axis:', np.cumsum(m, axis=0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Sum along the 0st axis: [[ 4  6]
 [ 8 10]]
Mean along the 0st axis: [[2. 3.]
 [4. 5.]]
Max along the 1st axis:: [[2 3]
 [6 7]]
Cumsum along the 0st axis: [[[ 0  1]
  [ 2  3]]

 [[ 4  6]
  [ 8 10]]]


### Binary ufuncs

Binary ufuncs are functions that take **two** ndarray as their input. 

For example:

- np.add: 	Addition (e.g., 1 + 1 = 2)
- np.subtract: Subtraction (e.g., 3 - 2 = 1)
- np.multiply:  Multiplication (e.g., 2 * 3 = 6)
- np.divide: Division (e.g., 3 / 2 = 1.5)
- np.floor_divide; 	Floor division (e.g., 3 // 2 = 1)


## Performance

In general, ufuncs (when applied to ndarrays directly) tend to be significantly faster than implementations that require iterating over a list.

The following example illustrates the difference in performance:

In [9]:
m = np.arange(4).reshape(2, 2)

print(np.add(m, m))

[[0 2]
 [4 6]]


In [91]:
m_list = list(range(1, 10**5))
m_array = np.array(m_list)

def list_reciprocal(l):
    return [1/v for v in m_list]        

In [92]:
# Time to compute the reciprocal with list iteration: ~1.82ms
%timeit list_reciprocal(m_list)

1.9 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [93]:
# reciprocal using the ufunc implementation (input: ndarray): 92.7 us
%timeit np.reciprocal(m_array)

94.1 µs ± 753 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [94]:
# reciprocal using the ufunc implementation (input: list): 2.43ms
# Requires an ndarray conversion (which most likely requires to iterate over the array). This causes an overhead.
# This causes the implementation to be slower than directly calling list_reciprocal() (!)
%timeit np.reciprocal(m_list)

2.44 ms ± 65.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Remark:** Avoid conversion from ndarrays to nested lists and vice versa whenever you can!

### Tip: Creating ufunc-like functions using np.vectorize()

The purpose of `np.vectorize()` is to transform functions which are not numpy-aware into functions that can operate on (and return) numpy arrays. The `np.vectorize(func)` automatically calls `func()` for every value in the numpy array. The returned values replace the items in the original matrix.

**Important remark: `np.vectorize()` is provided primarily for convenience, not for performance. The implementation is essentially a for loop**.

The example below illustrates how `np.vectorize()` can be applied in practice:

In [182]:
def elementwise_func(element):
    return 2*element if element % 2 else 3 * element

def iterating_func(matrix):

    for row_idx in range(matrix.shape[0]):
        for col_idx in range(matrix.shape[1]):
            element = matrix[row_idx, col_idx]
            element = 2 * element if element % 2 else 3 * element

            
    return matrix

vectorized_pow = np.vectorize(elementwise_func)

In [183]:
m = np.arange(1000**2).reshape(1000, 1000)

# We run time it since vectorize() is an inplace operation
# Using np.vectorize() results in a small performance gain
%timeit -n 1 vectorized_pow(m)

82.6 ms ± 4.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [184]:
m = np.arange(1000**2).reshape(1000, 1000)

# We run time it since iterating_func() is an inplace operation
%timeit -n 1 iterating_func(m)

110 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**The following code shows a fully vectorized implementation of the previous function. The fully vectorized implementation is almost 10 times faster!**

In [189]:
m = np.arange(1000**2).reshape(1000, 1000)
%timeit -n 1 np.where(m % 2 == 0, m * 3, m * 2)

9.9 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
